# Site settings
title: Duncan Graeme MacDonald Stuart - Web Developer
description: >
  Professional CV of Duncan Graeme MacDonald Stuart -
  a Senior Web Developer and Technical Architect
  based in Gothenburg, Sweden
baseurl: "/dgms_cv"
url: "https://dgmstuart.github.com"

# Build settings
markdown: kramdown
exclude: ['README.md', 'bin', 'Gemfile.lock', 'Gemfile']
